spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Blog?serverTimezone=CTT&characterEncoding=UTF-8
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml
